baseURL = "http://example.org/"
languageCode = "zh_TW"
title = "Sherry Dashboard Site"

defaultContentLanguage = "zh_TW"

theme = "sherrydashboard"
uglyURLs = false  #ugly:content/about.md=>https://example.org/about.html

[outputs]
   home = ["HTML", "RSS"]
   page = ["HTML", "RSS"]
   section = ["HTML", "RSS"]

[module]
   [[module.mounts]]
      source = 'content'
      target = 'content'

[languages.zh_TW] 
   languageCode = "zh_TW"

[menu]
  [[menu.main]]
    name = "首頁"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    pre = "receipt_long"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "標籤"
    pre = "mail_outline"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Logout"
    pre = "logout"
    url = "/"
    weight = 9
